plot4 <- function() {
  d <- read.csv("~/household_power_consumption.txt",sep=";",skip = 66636,nrows = 2880)
  colnames(d) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
  d$Date <- as.Date(d$Date,"%d/%m/%Y")
  d$DateTime <- strptime(paste(d$Date,d$Time,sep=" "),"%Y-%m-%d %H:%M:%S")
  png(file = "plot4.png")
  par(mfrow = c(2,2))
  plot(d$DateTime,d$Global_active_power,type = "l",xlab="",ylab="Global Active Power")
  plot(d$DateTime,d$Voltage,type = "l",xlab="datetime",ylab="Voltage")
  plot(d$DateTime,d$Sub_metering_1,type = "l",xlab="",ylab="Energy sub metering")
  lines(d$DateTime,d$Sub_metering_2,type = "l",col="red")
  lines(d$DateTime,d$Sub_metering_3,type = "l",col="blue")
  legend("topright",pch="_",col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(d$DateTime,d$Global_reactive_power,type = "l",xlab="datetime",ylab="Global_reactive_power")
  dev.off()
}